package exception.trycatch;

public class RuntimeEx {

	public static void main(String[] args) {
		
		// 실행 예외
		// null pointer
		
//		String str = null;
//		
//		str.charAt(1);
		
		// ArrayIndexBoundsException
		
//		int[] arr = {1, 2, 3};
//		arr[10] = 10;
		
		// NumberFormat
		
//		int a = 1;
//		System.out.println(a + ""); // 숫자를 문자열로
		
//		String s = "^^1";
//		int a = Integer.parseInt(s); 
//		System.out.println(a); // 문자열을 숫자로
		
		// ClassCasting
		
//		String s = (String)new Object();
	}
}
